{
 "title": "RAGStack",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Errors by LLM",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT llm, \n  COUNT(*) FILTER (WHERE error = false) as num_successes, \n  COUNT(*) FILTER (WHERE error = true) as num_errors,   \n  100.0 * COUNT(*) FILTER (WHERE error = true) / COUNT(*) AS error_rate\nFROM tests\nGROUP BY llm;\n"
    }
   ]
  },
  {
   "title": "Error/hour by LLM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT llm, (time::date || ' ' || extract(hour from time) || ':00:00')::timestamp, 100.0 * COUNT(*) FILTER (WHERE error = true) / COUNT(*) AS error_rate\nFROM tests\nGROUP BY llm, (time::date || ' ' || extract(hour from time) || ':00:00')::timestamp"
    }
   ]
  },
  {
   "title": "Latency by LLM",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT llm,  \n  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY latency) as P50, \n  PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY latency) as P90, \n  PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY latency) as P99,\n  STDDEV(latency) AS std_deviation, \n  AVG(latency) AS avg_latency,\n  MIN(latency) AS min_latency,\n  MAX(latency) AS max_latency\nFROM tests\nGROUP BY llm;"
    }
   ]
  },
  {
   "title": "Latency trend by LLM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT llm, latency, time\nFROM tests\n"
    }
   ]
  }
 ]
}