version: '3.8'


volumes:
  grafana_storage: {}

services:
  grafana:
    image: grafana/grafana-enterprise:9.4.7
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - 'grafana_storage:/var/lib/grafana'

 
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
